###########
# site.title, site.url, site.author.name

title: "Alex Esc's Short Links"
author: 
  name: 'Alex Esc.'
description: I host my short permanent links & temporary links here.

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: '/url'
url:  'https://alex-esc.github.io'
baseurl: '/url'

## Menu buttons


other:
  about: 'https://alex-esc.github.io/en_us/pages/about.html' # URL for your about me page, it can be your linked in or other social media account 

feeddescriptiononly: "Feed of my Public link bookmarks"
404message: "Double check you wrote the URL correctly, some links are temporary and may not be available anymore. Go to the link archive to search for the link you're looking for."

########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md


safe: true
lsi: false

plugins:
  - jekyll-redirect-from
  - jekyll-feed

excerpt_separator: <!--more-->

kramdown:
  auto_ids: true # Auto-generate ID's for headings
  
  
feed:
 tags:
  - linkbox